In [2]:
import pandas as pd

autos = pd.read_csv("../../datasets/autos.csv", encoding="latin1")

# Output five first lines
autos.head()

# Show infos
autos.info()

#Show colums
autos.columns

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   dateCrawled          50000 non-null  str
 1   name                 50000 non-null  str
 2   seller               50000 non-null  str
 3   offerType            50000 non-null  str
 4   price                50000 non-null  str
 5   abtest               50000 non-null  str
 6   vehicleType          44905 non-null  str
 7   yearOfRegistration   50000 non-null  int64
 8   gearbox              47320 non-null  str
 9   powerPS              50000 non-null  int64
 10  model                47242 non-null  str
 11  odometer             50000 non-null  str
 12  monthOfRegistration  50000 non-null  int64
 13  fuelType             45518 non-null  str
 14  brand                50000 non-null  str
 15  notRepairedDamage    40171 non-null  str
 16  dateCreated          50000 non-null  str
 17  nrOfPictures         50000 non-null  int64
 18  postalCode           50000 non-null  int64
 19  lastSeen             50000 non-null  str
dtypes: int64(5), str(15)
memory usage: 7.6 MB

Index(['dateCrawled', 'name', 'seller', 'offerType', 'price', 'abtest',
       'vehicleType', 'yearOfRegistration', 'gearbox', 'powerPS', 'model',
       'odometer', 'monthOfRegistration', 'fuelType', 'brand',
       'notRepairedDamage', 'dateCreated', 'nrOfPictures', 'postalCode',
       'lastSeen'],
      dtype='str')

Data Cleaning
Convert to snake_case

In [3]:
clean_columns = ['date_crawled', 'name', 'seller', 'offer_type', 'price', 'ab_test',
                      'vehicle_type', 'registration_year', 'gearbox', 'power_ps', 'model',
                      'odometer', 'registration_month', 'fuel_type', 'brand',
                      'unrepaired_damage', 'ad_created', 'num_pictures', 'postal_code',
                      'last_seen']

autos.columns = clean_columns

# Check if any data need more cleaning
autos.describe(include="all") # include="all" to include all the columns

,date_crawled,name,seller,offer_type,price,ab_test,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,num_pictures,postal_code,last_seen
count,50000,50000,50000,50000,50000,50000,44905,50000.000000,47320,50000.000000,47242,50000,50000.000000,45518,50000,40171,50000,50000.0,50000.000000,50000
unique,48213,38754,2,2,2357,2,8,NaN,2,NaN,245,13,NaN,7,40,2,76,NaN,NaN,39481
top,2016-04-04 16:40:33,Ford_Fiesta,privat,Angebot,$0,test,limousine,NaN,manuell,NaN,golf,"150,000km",NaN,benzin,volkswagen,nein,2016-04-03 00:00:00,NaN,NaN,2016-04-07 06:17:27
freq,3,78,49999,49999,1421,25756,12859,NaN,36993,NaN,4024,32424,NaN,30107,10687,35232,1946,NaN,NaN,8
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005.073280,NaN,116.355920,NaN,NaN,5.723360,NaN,NaN,NaN,NaN,0.0,50813.627300,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.712813,NaN,209.216627,NaN,NaN,3.711984,NaN,NaN,NaN,NaN,0.0,25779.747957,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.000000,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.0,1067.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999.000000,NaN,70.000000,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,0.0,30451.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003.000000,NaN,105.000000,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,0.0,49577.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008.000000,NaN,150.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,0.0,71540.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.000000,NaN,17700.000000,NaN,NaN,12.000000,NaN,NaN,NaN,NaN,0.0,99998.000000,NaN

Per observation some columns have only 2 uniques values let explore

In [4]:
unique_columns = ["seller", "offer_type", "ab_test", "gearbox", "unrepaired_damage"]

for item in unique_columns:
    print('-'*30)
    print(autos[item].value_counts())
    print('-'*30)

------------------------------
seller
privat        49999
gewerblich        1
Name: count, dtype: int64
------------------------------
------------------------------
offer_type
Angebot    49999
Gesuch         1
Name: count, dtype: int64
------------------------------
------------------------------
ab_test
test       25756
control    24244
Name: count, dtype: int64
------------------------------
------------------------------
gearbox
manuell      36993
automatik    10327
Name: count, dtype: int64
------------------------------
------------------------------
unrepaired_damage
nein    35232
ja       4939
Name: count, dtype: int64
------------------------------

NB: When column are too one-sided there is low chance to have helpful information from them

In [5]:
autos['num_pictures'].value_counts() # all value is 0 here

#Lets drop columns who is not helpful for us
autos.drop(["seller", "offer_type", "num_pictures"], axis="columns", inplace=True)

autos.info()

autos.head()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date_crawled        50000 non-null  str
 1   name                50000 non-null  str
 2   price               50000 non-null  str
 3   ab_test             50000 non-null  str
 4   vehicle_type        44905 non-null  str
 5   registration_year   50000 non-null  int64
 6   gearbox             47320 non-null  str
 7   power_ps            50000 non-null  int64
 8   model               47242 non-null  str
 9   odometer            50000 non-null  str
 10  registration_month  50000 non-null  int64
 11  fuel_type           45518 non-null  str
 12  brand               50000 non-null  str
 13  unrepaired_damage   40171 non-null  str
 14  ad_created          50000 non-null  str
 15  postal_code         50000 non-null  int64
 16  last_seen           50000 non-null  str
dtypes: int64(4), str(13)
memory usage: 6.5 MB

,date_crawled,name,price,ab_test,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÜV_neu_ist_sehr_gepfleg...,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,39218,2016-04-01 14:38:50

Transalation of non english words
Lets display unique values to check the germann words

In [6]:
german_columns = ["vehicle_type", "gearbox", "fuel_type", "unrepaired_damage"]

for column in german_columns:
    print()
    print(f'{column}: {autos[column].unique()}') # print unique values
    
translations = {# vehicle type terms
               'bus':'bus',
               'limousine':'limousine',
               'kleinwagen': 'small car',
               'kombi': 'combo',
               'coupe':'coupe',
               'suv':'suv',
               'cabrio': 'cabrio',
               'andere': 'other',
               'cabrio': 'convertible',
               # gear box terms
               'manuell': 'manual',
               'automatik': 'automatic',
               # fuel type terms
               'lpg':'lpg',
               'benzin': 'gasoline',
               'diesel':'diesel',
               'cng':'natural gas',
               'hybrid':'hybrid',
               'elektro':'electric',
               'andere':'other',
               # unrepaired damage terms
               'nein':'no',
               'ja':'yes'}

def column_translator(df, column, dict_value):
    '''Translates values in df column using value_dict as reference'''
    df[column] = df[column].map(dict_value) #each key will be change to its values
    

for item in german_columns:
    column_translator(df=autos, column=item, dict_value=translations)
    
    
for column in german_columns:
    print()
    print(f'{column}: {autos[column].unique()}') # print unique values

vehicle_type: <StringArray>
[       'bus',  'limousine', 'kleinwagen',      'kombi',          nan,
      'coupe',        'suv',     'cabrio',     'andere']
Length: 9, dtype: str

gearbox: <StringArray>
['manuell', 'automatik', nan]
Length: 3, dtype: str

fuel_type: <StringArray>
['lpg', 'benzin', 'diesel', nan, 'cng', 'hybrid', 'elektro', 'andere']
Length: 8, dtype: str

unrepaired_damage: <StringArray>
['nein', nan, 'ja']
Length: 3, dtype: str

vehicle_type: <StringArray>
[        'bus',   'limousine',   'small car',       'combo',           nan,
       'coupe',         'suv', 'convertible',       'other']
Length: 9, dtype: str

gearbox: <StringArray>
['manual', 'automatic', nan]
Length: 3, dtype: str

fuel_type: <StringArray>
['lpg', 'gasoline', 'diesel', nan, 'natural gas', 'hybrid', 'electric',
 'other']
Length: 8, dtype: str

unrepaired_damage: <StringArray>
['no', nan, 'yes']
Length: 3, dtype: str

Lets convert now non numeric values to numeric

In [7]:
autos["price"] = (autos["price"].
                  str.replace('$','')
                    .str.replace(',','')
                    .astype(int))

autos['odometer'] = (autos['odometer']
                    .str.replace('km','')
                    .str.replace(',','')
                    .astype(int))

autos.rename(columns={"price":"price_usd", 'odometer': 'odometer_km'}, inplace=True)

autos["price_usd"].head()

0    5000
1    8500
2    8990
3    4350
4    1350
Name: price_usd, dtype: int64

In [13]:
print(autos[['odometer_km', 'price_usd']].describe())

         odometer_km     price_usd
count   50000.000000  5.000000e+04
mean   125732.700000  9.840044e+03
std     40042.211706  4.811044e+05
min      5000.000000  0.000000e+00
25%    125000.000000  1.100000e+03
50%    150000.000000  2.950000e+03
75%    150000.000000  7.200000e+03
max    150000.000000  1.000000e+08

Based on the analysis of the mileage values, 150,000 km is not an outlier.

However, the price data does not seem reliable, given the minimum and maximum prices and the corresponding mileage values.

Lets explore and remove the outlier for price_usd

In [14]:
autos["price_usd"].describe()

count    5.000000e+04
mean     9.840044e+03
std      4.811044e+05
min      0.000000e+00
25%      1.100000e+03
50%      2.950000e+03
75%      7.200000e+03
max      1.000000e+08
Name: price_usd, dtype: float64

Lets compute the IQR (Interquantile Range) to keep data inside this range

Interquartile Range (IQR) = 75th Percentile - 25th Percentile
Lower fence = 25th Percentile - 1.5*(IQR)
Upper fence = 75th Percentile + 1.5*(IQR)

In [16]:
price_25, price_75 = (1100, 7200)

IQR = price_75 - price_25
lower_fence = price_25 - 1.5*IQR
upper_fence = price_75 + 1.5*IQR

print(f'Interquartile Range: {IQR}')
print(f'Lower fence: {lower_fence}')
print(f'Upper fence: {upper_fence}')

Interquartile Range: 6100
Lower fence: -8050.0
Upper fence: 16350.0

In [17]:
autos["price_usd"].value_counts()

price_usd
0         1421
500        781
1500       734
2500       643
1200       639
          ...
145000       1
130000       1
385          1
22200        1
16995        1
Name: count, Length: 2357, dtype: int64

Of the 50,000 rows in our dataset, 1,421 records (~3%) are listed at zero price. Since this percentage is very low, we can safely remove these entries. We will set our lower fence at 1 to exclude zero prices.

In [21]:
autos = autos[autos['price_usd'].between(1, upper_fence)]
autos.describe()

,price_usd,registration_year,power_ps,odometer_km,registration_month,postal_code
count,44795.000000,44795.00000,44795.000000,44795.000000,44795.000000,44795.000000
mean,4089.433620,2003.97339,109.394910,129762.361871,5.744012,50502.431789
std,3841.429247,74.81955,205.150622,36398.554742,3.707064,25726.937446
min,1.000000,1000.00000,0.000000,5000.000000,0.000000,1067.000000
25%,1150.000000,1999.00000,68.000000,125000.000000,3.000000,30159.000000
50%,2700.000000,2003.00000,102.000000,150000.000000,6.000000,49356.000000
75%,5999.000000,2007.00000,140.000000,150000.000000,9.000000,71069.000000
max,16350.000000,9999.00000,17700.000000,150000.000000,12.000000,99998.000000

Now lets explore date column